[package]
name = "celari_token_bridge"
type = "contract"
authors = ["Celari Team"]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.1.2", directory = "noir-projects/aztec-nr/aztec" }
bridged_token = { path = "../bridged_token" }
